### ISSUE TITLE
Does not appear to contain CMakeLists.txt.

### ISSUE THREAD

**Issue by mahi045** [daajoe/dynasp#1]
I was trying to `build sharp` inside folder `/dynasp/sharp` according to instructions in [README.md](https://github.com/daajoe/dynasp/blob/master/README.md). But I got the following error message:

CMake Error: The source directory ~~"/home/mahi/Study/dynasp/sharp"~~ does not appear to contain CMakeLists.txt.

Also got same error when I tried to build `dynasp` inside folder `/dynasp`. 
My cmake version is `3.5.1`.
I cloned the **master branch** code

**Comment by daajoe** [comment]
Atm the build via cmake works only for the non-master branches. For the master branch see: https://www.dbai.tuwien.ac.at/research/project/sharp/ (it requires autoconf).
Sorry for the inconvenience.

**Comment by mahi045** [comment]
Thanks for your response.
