### ISSUE TITLE
'configure.ac' or 'configure.in' is required

### ISSUE THREAD

**Issue by mahi045** [daajoe/dynasp#2]
After reading your comment ([comment link](https://github.com/daajoe/dynasp/issues/1#issuecomment-437699344)) I have checkout the branch `2nd-lvl-opt`.
I have successfully installed `htd` and `sharp` library according to **INSTALL** file in the corresponding folders.

To install `dynasp`, I have tried to follow the instructions in **INSTALL** ([Link here](https://github.com/daajoe/dynasp/blob/2nd-lvl-opt/INSTALL)) file. The first command for compilation is `./configure`.

As there is no **configure** file in the folder, command `./configure` was failed. 

I have also tried to generate **configure** using `autoconf`.  But to generate it using `autoconf`, `configure.ac` or `configure.in` is required.

**Comment by hmarkus** [comment]
Please checkout branch 2nd-lvl-opt-performance
