### ISSUE TITLE
make: *** No rule to make target '...'

### ISSUE THREAD

**Issue by mahi045** [daajoe/dynasp#3]
I have downloaded the code of release `v2.2.0` [link here](https://github.com/daajoe/dynasp/releases/tag/v2.0.0).
I have installed `libhtd.so` and `libsharp.so` library successfully.
Inside directory `dynasp`, I have configured the package for my system using command `./configure`.
Then I have tried to compile using command `make`. But I have got the error: `make: *** No rule to make target 'src/parsers/LParseBisonParser.hh', needed by 'check'.  Stop.`
It also seems that for some other targets there is no rules to make.

**Comment by hmarkus** [comment]
Sorry, apparently there is some strange bison/automake incompatibility on some machines/distros.
Can you maybe try to copy the bison files (https://www.dropbox.com/sh/5xvck5mgrz4sxr3/AACgHpOchG-MKc8Xpm3PlDa-a?dl=0) to your setup?

**Comment by mahi045** [comment]
Thank you @hmarkus . This is helpful. Now it is installed properly.
