### ISSUE TITLE
make: *** No rule to make target 'stack.hh', needed by 'all'.  Stop.

### ISSUE THREAD

**Issue by MRJasonP** [daajoe/dynasp#4]
Hi,
I download the dynasp under master branch from here: https://github.com/daajoe/dynasp.
I successfully compiled htd and sharp. 
However when I run "`sudo make`" for dynasp. 
I got this error at the beginning: 
"make: *** No rule to make target 'src/parsers/LParseBisonParser.hh', needed by 'all'.  Stop." 
I referred to this issue ticket: https://github.com/daajoe/dynasp/issues/3, and solved this problem. Then I run "`sudo make`" again, I got this error message: 
"make: *** No rule to make target 'stack.hh', needed by 'all'.  Stop."
Any help will be grateful.

**Comment by hmarkus** [comment]
Did you try also stack.hh included in https://www.dropbox.com/sh/5xvck5mgrz4sxr3/AACgHpOchG-MKc8Xpm3PlDa-a?dl=0?

**Comment by MRJasonP** [comment]
I put all of four into "dyasp/src/parsers" at the beginning. And now I pull "stach.hh", "posiiton.hh", and "location.hh" into root folder "dyasp/". I re-run the `sudo make`. A new error pops up:

CXX      src/parsers/LParseBisonParser.lo
In file included from src/parsers/LParseBisonParser.yy:8:0:
src/parsers/LParseLexer.hpp:34:24: error: expected ‘)’ before ‘istream’
   LParseLexer(FLEX_STD istream *in = NULL, FLEX_STD ostream *out = NULL);
                        ^~~~~~~

**Comment by hmarkus** [comment]
Which version of bison do you have installed?

**Comment by hmarkus** [comment]
Do you also have flex installed? Which version?

**Comment by MRJasonP** [comment]
3.0.4 on bison
2.6.4 on flex

**Comment by hmarkus** [comment]
Have you tried putting the files from dropbox to dynasp/src/parsers?

**Comment by MRJasonP** [comment]
Yes, I put all files from dropbox to dynasp/src/parsers. If I just put all files into dynasp/src/parsers, I will get such errors like:
make: *** No rule to make target 'stack.hh', needed by 'all'.  Stop.
make: *** No rule to make target 'position.hh', needed by 'all'.  Stop.
make: *** No rule to make target 'location.hh', needed by 'all'.  Stop.

I checked my Makefile.am. It has:

```
#----------------------------#
# libdynasp.la build options #
#----------------------------#

# list of generated header files
LIBDYNASP_GENERATED_HEADER = \
	src/parsers/LParseBisonParser.hh \
	stack.hh \
	position.hh \
	location.hh
```

So I put these three files into dynasp/ folder. (Also keep copies in dynasp/src/parsers)
Then the error I described previously occurs:

> I put all of four into "dyasp/src/parsers" at the beginning. And now I pull "stach.hh", "posiiton.hh", and "location.hh" into root folder "dyasp/". I re-run the `sudo make`. A new error pops up:
> 
> CXX src/parsers/LParseBisonParser.lo
> In file included from src/parsers/LParseBisonParser.yy:8:0:
> src/parsers/LParseLexer.hpp:34:24: error: expected ‘)’ before ‘istream’
> LParseLexer(FLEX_STD istream *in = NULL, FLEX_STD ostream *out = NULL);
> ^~~~~~~

**Comment by hmarkus** [comment]
Hmm.. do you also have the dev packages of bison and flex, e.g., libfl-dev
in ubtuntu?

**Comment by MRJasonP** [comment]
Yes, I run this at the very beginning:
`sudo apt-get install git libgmp-dev libtool-bin flex bison g++
`
Now I run again, it returns:

bison is already the newest version (2:3.0.4.dfsg-1build1).
flex is already the newest version (2.6.4-6).
libgmp-dev is already the newest version (2:6.1.2+dfsg-2).
libtool-bin is already the newest version (2.4.6-2).
g++ is already the newest version (4:7.3.0-3ubuntu2.1).
git is already the newest version (1:2.17.1-1ubuntu0.4).

**Comment by MRJasonP** [comment]
And yes,  I am running on Ubuntu 18.04.1 LTS

**Comment by hmarkus** [comment]
Hmm.. Apparently the newer versions do not define FLEX_STD and it's a
combination of new libstdc++ and flex library.

Can you add

#ifndef FLEX_STD

#define FLEX_STD std::

#endif


to src/parsers/LParseLexer.hpp as in
https://github.com/westes/flex/issues/124?

**Comment by MRJasonP** [comment]
Sorry for bothering too much. But two new errors pop up
`CXX      src/main.o
src/main.cpp: In function ‘int main(int, char**)’:
src/main.cpp:336:26: error: cannot declare variable ‘algorithm’ to be of abstract type ‘dynasp::DynAspAlgorithm’
  dynasp::DynAspAlgorithm algorithm;
                          ^~~~~~~~~
`
and

`src/main.cpp:343:111: error: no matching function for call to ‘sharp::ITreeSolver::decompose(dynasp::IGroundAspInstance&, const bool&, const unsigned int&, const bool&)’
 ition> td(solver->decompose(*instance, opts.weak, opts.children, opts.tdopt));
`

For the second error, I checked `~/.local/usr/lib`, I can only see "libhtd.so". But under `/usr/local/lib`, I can see both "libsharp.so" and "libhtd.so". So I tried to move sharp related files to `~/.local/usr/lib`, but it still could not work.

**Comment by hmarkus** [comment]
Hmm.. looks just like misconfigured paths.
So you did call make install for sharp?

**Comment by hmarkus** [comment]
Did you already compile/find libdynasp.la in your lib folders? As main.cpp
is the last file to compile for dynasp binary, it looks like you are almost
through :).

**Comment by MRJasonP** [comment]
Yes, I called "make install" for sharp, and it did compile and install successfully(I think). 
Which lib folder you're indicating, for "libdynasp.la", I could not find in both `~/local/usr/lib` and `/usr/local/lib` :(

**Comment by hmarkus** [comment]
What does "make libdynasp.la" do?

**Comment by MRJasonP** [comment]
Ohh. "libdynasp.la" is actually in dynasp folder. I run "make libdynasp.la", and it compiles fine besides a couple of warnings. 

And you're right, just need to compile the last main file..

**Comment by hmarkus** [comment]
Hmmm.. sorry. I start to wonder.. Are you in master branch? I think sharp
is newer than that branch of dynasp is capable of.
Can you please try branches 2nd-lvl-opt or 2nd-lvl-opt-performance?
Sorry for inconvenience.

**Comment by MRJasonP** [comment]
Yes, I download from the master branch. And this should be the htd version I downloaded:https://github.com/mabseher/htd/tree/3280fb02a4712b9926904e875a26cb41e0f841ef
and this is the sharp I used:
https://github.com/daajoe/sharp/tree/31bd32e8a6d05fe16e3457d7b3dd2d4764922696

Sure I will try other branches as you provided, and let you know.
 I appreciate your help

**Comment by MRJasonP** [comment]
I tried both 2nd-lvl-opt and 2nd-lvl-opt-performance branches. Both htd and sharp compile fine. But when I finally use cmake to compile dynasp, both of these two branches return a same error:

`CMake Error: File /dynasp_v3/dynasp_compile/cmake/cmake_uninstall.cmake.in does not exist.
CMake Error at CMakeLists.txt:53 (configure_file):
  configure_file Problem configuring file
`
According to https://github.com/curl/curl/issues/1755, it seems like we have a missing file?

**Comment by hmarkus** [comment]
Can you do it with the same build system as before, so not use CMake?
CMake was added later and is not maintained.

**Comment by MRJasonP** [comment]
Please point me out if I am wrong. If I use the same build system, when building "dynasp", I assume I need to call `bash autogen.sh` first, right?  But it returns 
`bash autogen.sh 
autoreconf: 'configure.ac' or 'configure.in' is required
`
This is the version I download from 2nd-lvl-opt-performance branch, I checked 2nd-lvl-opt branch, there was no such file as well.

**Comment by hmarkus** [comment]
Yes. Can you please copy build system from the master branch? I will update
the master branch soon, such that it works, atm I just have limited access
to a PC :(.

**Comment by MRJasonP** [comment]
Would you please provide an environment that the system can be successfully compiled? Or maybe a list of software version that can compile the system.

**Comment by hmarkus** [comment]
I will update the version in the next couple of days.


Am Do., 28. Feb. 2019 um 21:42 Uhr schrieb tjpjx2012 <
notifications@github.com>:

**Comment by hmarkus** [comment]
I pushed the new version 2.5 of dynasp to branch
2nd-lvl-opt-performance, see:
https://github.com/daajoe/dynasp/tree/2nd-lvl-opt-performance
This includes also updated htd library, sharp library and compatibility for
ubuntu 18.10.
Everything should now work out of the box.

Am Fr., 1. März 2019 um 16:49 Uhr schrieb markus hecher <mhecher@gmail.com>:
