### ISSUE TITLE
td->maximumBagSize() <= 15 failed

### ISSUE THREAD

**Issue by mahi045** [daajoe/dynasp#5]
Hi,
I want to know how to solve the following failure:
```
src/IterativeTreeSolver.cpp:300: virtual htd::ITreeDecomposition* sharp::IterativeTreeSolver::decompose(const sharp::IInstance&, bool, unsigned int, bool) const: Assertion `td->maximumBagSize() <= 15' failed
```
Is it the case the treewidth is too high so that Dynasp cannot count answer sets?
Thanks in advance.

**Comment by hmarkus** [comment]
Given that the decision problem is double exponential (assuming ETH), there is not much hope to try for larger treewidth here. You could uncomment this line and replace in include/dynasp/global the line #define INT16_ATOMS_TYPE
by #define INT32_ATOMS_TYPE.  However, I guess you won't be able to improve solving...
